
#a = 2.721, 1.916, 1.827
#zo = 0.409, 0.408, 0.332
#km = 0.129, 0.076, 0.093
#k_t = 0.179, 0.014
#fo_t = 0.49, 0.21

des:
  pr_a: [2.721, 1.916, 1.916, 1.827, 1.827, 1.827]
  pr_zo: [0.409, 0.408, 0.408, 0.332, 0.332, 0.332]
  pr_km: [0.129, 0.076, 0.076, 0.093, 0.093, 0.093]
  pr_k_t: [ 0.179,  0.014,  0.014]
  pr_fo_t: [ 0.49 ,  0.105,  0.105]

  min_magerr: 0.05
  max_magerr: 0.5
  min_rms: 0.1

  ncalc: 200
  nmax: 1000
  undet: 99
  zmax: 2.
  use_split: False
  catalog: "/Users/marberi/data/des_mice/*.dat.h5"
  columns: "/Users/marberi/photoz/run/des_data/mock.columns"
  filters: ['des_g', 'des_r', 'des_i', 'des_z', 'des_Y']
  data_dir: '/Users/marberi/photoz/run/des_data'
  filter_dir: 'filters/DES'
  use_cache: False
  use_par: True
  dz: 0.005
  odds: 0.68
  in_format: 'hdf5'
