standard:
  res_fmt: '{0}.res'
  sed_fmt: '{0}.sed'
  c: ''
  in_format: 'ascii'
  out_format: 'ascii'
  use_priors: True
  ncalc: 100
  nmax: 10000
  seds: ['Ell_01', 'Sbc_01', 'Scd_01', 'Irr_01', 'Irr_14', 'I99_05Gy']

  nell: 1
  nsp: 2
  nsb: 3  
  # Previously used priors..
#  pr_a: [2.369,1.843,1.340]
#  pr_zo: [0.387,0.390,0.208]
#  pr_km: [0.119,0.093,0.130]
#  pr_fo_t: [0.48,0.22]
#  pr_k_t: [0.186,0.038]

  pr_a: [2.465,  1.806,  0.906]
  pr_zo: [0.431,  0.390,  0.0626]
  pr_km: [0.0913, 0.0636, 0.123]
  pr_fo_t: [0.35, 0.5]
  pr_k_t: [0.450,  0.147]

  hh_fac: 0.
  hz_fac: 0.
 
  sn_lim: 5. 
  from_space: []
  use_snlim: False
  snlim_sig: 5.

#  use_cache: False
  use_cache: True
  tblock: True
  dz_bright: 0.001
  dz_faint: 0.005
  min_rms_bright: 0.0055
  min_rms_faint: 0.055
  min_magerr: 0.0
  max_magerr: 10.
  mag_split: 22.5
  use_split: False
  opt: True
  others: []
  order: ['id', 'zb', 'zb_min', 'zb_max', 't_b', 'odds', 'z_ml', 't_ml', 'chi2', 'zs', 'm0']
  m_step: 0.1
  output: ''
  
  D_tel: 4.2
  D_tel_space: 4.2
  aperture: 2.0
  pixscale: 0.27
  pixscale_space: 0.27
  n_exp: 2.
  n_exp_space: 2.
  RN: 5.
  RN_space: 5.
  dnoise: 0.
  dnoise_space: 0.
  trays: 'tray_matrix_42NB.txt'
  exp_t1: 45
  exp_t2: 45
  exp_t3: 50
  exp_t4: 60
  exp_t5: 75

  exp_up: 45
  exp_g: 45
  exp_r: 50
  exp_i: 75
  exp_z: 75
  exp_y: 75

  # EUCLID NIR Bands (temporary exposure times)
  exp_Y: 75
  exp_J: 75
  exp_H: 75
  exp_vis: 100

  # SN limits in the different bands...
  #
  #

  snlim_g: 25.35 
  snlim_r: 24.85
  snlim_i: 25.05
  snlim_z: 24.65

  snlim_Y: 24.
  snlim_J: 24.
  snlim_H: 24.

  trays: 
    [[4500, 4600, 4700, 4800, 4900, 5000, 5100, 5200],
     [5300, 5400, 5500, 5600, 5700, 5800, 5900, 6000],
     [6100, 6200, 6300, 6400, 6500, 6600, 6700, 6800],
     [6900, 7000, 7100, 7200, 7300, 7400, 7500, 7600],
     [7700, 7800, 7900, 8000, 8100, 8200, 8300, 8400]]

#  exp_trays: [45,45,45,50,60,70]
  vign: [1.,0.75, 0.375]
  sky_spec: 'sky_spectrum.txt'
  
  add_noise: False
  old_model: False
  ab_tmp: 'ab'
  zmax_ab: 12.
  dz_ab: 0.01
  prior: 'pau'
  train: False
  norm_flux: False
  cache_dir: '/disks/shear9/marberi/cache/'
  data_dir: 'data'
  ab_dir: 'ab'
  filter_dir: 'filters'
  filters: ['u', 'g', 'r', 'z', 'y']
  sed_dir: 'seds'
  p_min: 0.01
  mag: True
  spectra: 'spectras.txt'
  get_z: True
  use_par: True
  nthr: 0
  columns: 'mock.columns'
  zp_offsets: 0.
  ntypes: []
  madau: False
  new_ab: False
  exclude: []
  zmin: 0.01
  zmax: 10.
  unobs: -99.
  undet: 99.
  delta_m0: 0.
  n_peaks: 1
  verbose: False
  cat: ''
  interp: 2
  prior: 'pau'
  dz: 0.01
  odds: 0.68
  min_rms: 0.05
  hdf5_node: '/cat/cat'
  mag_fmt: '{0}'
  err_fmt: '{0}'
  from_bcnz: ['id', 'zb', 'zb_min', 'zb_max', 't_b', 'odds', 'z_ml', 't_ml', 'chi2', 'zs', 'm0']
  prior_mag: 'i'

  out_pdf: False
  out_pdftype: False

  m_int: [20, 26]
  mN: 20
