
sv:
  pr_a: [3.588, 2.734, 2.734, 1.689, 1.689, 1.689]
  pr_zo: [0.608, 0.479, 0.479, 0.226, 0.226, 0.226]
  pr_km: [0.059, 0.101, 0.101, 0.105, 0.105, 0.105]
  pr_k_t: [0.477, 0.0, 0.0]

  catalog: '/Users/marberi/data/sv/dessv.hdf5'
  in_format: 'hdf5'
  filter_dir: '/Users/marberi/work/des/DES@BLANCO'
  filters: ['g', 'r', 'i', 'z', 'y']
  min_magerr: 0.05
  max_magerr: 0.5
  min_rms: 0.067
  interp: 8
  sed_dir: '/Users/marberi/work/des/CWWSB'
  spectra: '/Users/marberi/work/des/CWWSB/CWWSB.list'
  seds: ['El_cww','Sbc_cww','Scd_cww','Im_cww','SB3_kin','SB2_kin']
  sky_spec: '/Users/marberi/photoz/run/sky_spectrum.txt'
  pre_mag: 'mag_detmodel_'
  pre_err: 'magerr_detmodel_'

  mag_fmt: 'mag_detmodel_{}'
  err_fmt: 'magerr_detmodel_{}'

#  order: ['id', 'zb', 'zb_min', 'zb_max', 't_b', 'odds', 'z_ml', 't_ml', 'chi2', 'z_s', 'm_0']
  order: ['zb', 'ra', 'dec', 'odds', 'spread_model_i']

  unobs: 0.
  undet: 99.
